name: Build and Upload a Container image using tox
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tox_environment:
        type: string
        default: "docker"
        required: false
      tox_posargs:
        type: string
        default: ""
        required: false
      registry:
        required: false
        type: string
        default: quay.io
      registry_user:
        required: false
        default: maxhoesel_homelab
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    name: "Build and Push Container"
    runs-on: ubuntu-22.04
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3"
      - name: Set up pip and install tox
        run: |
          pip3 install --upgrade pip
          pip3 install "tox>=3,<4"

      - name: Build Container
        run: tox -e ${{ inputs.tox_environment }} -- ${{ inputs.tox_posargs }}

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Publish execution environment on registry
        run: docker push ${{ inputs.registry }}/${{ inputs.registry_user }}/${{ inputs.image_name }}
